[package]
name = "lua-persistent-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.9", features = ["lua54"] }

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
strip = true


