[package]
name = "lua-wasm-host"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "15.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# For persistent storage
sled = "0.34"  # Embedded database for persistence